// Code generated by MockGen. DO NOT EDIT.
// Source: payments.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	models "github.com/cko-recruitment/payment-gateway-challenge-go/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockPaymentsRepository is a mock of PaymentsRepository interface.
type MockPaymentsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentsRepositoryMockRecorder
}

// MockPaymentsRepositoryMockRecorder is the mock recorder for MockPaymentsRepository.
type MockPaymentsRepositoryMockRecorder struct {
	mock *MockPaymentsRepository
}

// NewMockPaymentsRepository creates a new mock instance.
func NewMockPaymentsRepository(ctrl *gomock.Controller) *MockPaymentsRepository {
	mock := &MockPaymentsRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentsRepository) EXPECT() *MockPaymentsRepositoryMockRecorder {
	return m.recorder
}

// AddPayment mocks base method.
func (m *MockPaymentsRepository) AddPayment(ctx context.Context, payment models.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPayment", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPayment indicates an expected call of AddPayment.
func (mr *MockPaymentsRepositoryMockRecorder) AddPayment(ctx, payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPayment", reflect.TypeOf((*MockPaymentsRepository)(nil).AddPayment), ctx, payment)
}

// GetPayment mocks base method.
func (m *MockPaymentsRepository) GetPayment(ctx context.Context, id string) *models.Payment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayment", ctx, id)
	ret0, _ := ret[0].(*models.Payment)
	return ret0
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockPaymentsRepositoryMockRecorder) GetPayment(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockPaymentsRepository)(nil).GetPayment), ctx, id)
}
