// Code generated by MockGen. DO NOT EDIT.
// Source: validation.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	models "github.com/cko-recruitment/payment-gateway-challenge-go/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockValidationService is a mock of ValidationService interface.
type MockValidationService struct {
	ctrl     *gomock.Controller
	recorder *MockValidationServiceMockRecorder
}

// MockValidationServiceMockRecorder is the mock recorder for MockValidationService.
type MockValidationServiceMockRecorder struct {
	mock *MockValidationService
}

// NewMockValidationService creates a new mock instance.
func NewMockValidationService(ctrl *gomock.Controller) *MockValidationService {
	mock := &MockValidationService{ctrl: ctrl}
	mock.recorder = &MockValidationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationService) EXPECT() *MockValidationServiceMockRecorder {
	return m.recorder
}

// ValidatePaymentRequest mocks base method.
func (m *MockValidationService) ValidatePaymentRequest(ctx context.Context, req models.PaymentRequest) []models.ValidationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePaymentRequest", ctx, req)
	ret0, _ := ret[0].([]models.ValidationError)
	return ret0
}

// ValidatePaymentRequest indicates an expected call of ValidatePaymentRequest.
func (mr *MockValidationServiceMockRecorder) ValidatePaymentRequest(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePaymentRequest", reflect.TypeOf((*MockValidationService)(nil).ValidatePaymentRequest), ctx, req)
}
